# Generated by Django 5.2.5 on 2025-08-21 05:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_date', '-priority'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='color',
            field=models.CharField(default='#667eea', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 21, 5, 50, 45, 391054, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='technology',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 21, 5, 51, 7, 54232, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, default='', help_text='Live demo URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Short description for project cards'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed description for project detail page'),
        ),
        migrations.AlterField(
            model_name='project',
            name='documentation_url',
            field=models.URLField(blank=True, default='', help_text='Documentation URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery',
            field=models.TextField(blank=True, help_text='Comma-separated image URLs for gallery'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main project image', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('on-hold', 'On Hold'), ('archived', 'Archived')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#667eea', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fab fa-python)', max_length=100),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry_type', models.CharField(choices=[('collaboration', 'Collaboration'), ('hiring', 'Hiring'), ('question', 'Question'), ('feedback', 'Feedback'), ('other', 'Other')], default='question', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='home.project')),
            ],
            options={
                'verbose_name': 'Project Inquiry',
                'verbose_name_plural': 'Project Inquiries',
                'ordering': ['-created_date'],
            },
        ),
    ]
