# Generated by Django 5.2.5 on 2025-08-24 04:45

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_project_options_projectcategory_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinquiry',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='detailed_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentation_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='project',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='created_date',
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload project documentation (max 100MB). Only PDF files allowed.', null=True, upload_to=home.models.project_pdf_path, validators=[home.models.validate_file_size, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload project image (max 10MB). Supported formats: JPG, PNG, GIF, WebP', null=True, upload_to=home.models.project_image_path, validators=[home.models.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('on-hold', 'On Hold')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='color',
            field=models.CharField(default='#6B7280', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS class or icon name', max_length=50),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='home_projec_status_12a81a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['featured'], name='home_projec_feature_ce6a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='home_projec_priorit_c85079_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_date'], name='home_projec_created_6bf714_idx'),
        ),
        migrations.DeleteModel(
            name='ProjectInquiry',
        ),
    ]
